### ISSUE TITLE
Possibility to set a higher scroll speed ?

### ISSUE THREAD

**Issue by ghost** [jbensmann/xmouseless#1]
When using    
 { XK_p,        4 }, scroll up
 { XK_n,        5 }, scroll down

Is it possible to set a higher speed for the navigation in a web browser for instance ?

**Comment by jbensmann** [comment]
This is currently not possible, I have already thought about how to do that. The ideal solution would be to scroll continuously while holding down the keys, I will look into it when I have time.

**Comment by jbensmann** [comment]
Added bindings to scroll continuously.
