### ISSUE TITLE
Multiple actions on keypress? (for example click and notification)

### ISSUE THREAD

**Issue by Combowombo** [jbensmann/xmouseless#13]
How do I configure config.h so that I can execute two or more actions on a key press? for example maybe I want to click and then have notify-send show that I clicked. Or click and have notify-send show that I've exited xmouseless and then exit out of the program?

**Comment by jbensmann** [comment]
Generally it should be possible to bind the same key to multiple actions, have you tried that? If that does not work it might be that notify-send does not work while xmouseless is running.

**Comment by Combowombo** [comment]
hmmm okay I'll give that a try, I need to brush up on my C in order to do so. so for example if i wanted scroll up to scroll five times would i do something like the following?

/* 1: left
 * 2: middle
 * 3: right */
static ClickBinding click_bindings[] = {
    /* key         button */  
    { XK_u,        1 },
    { XK_i,        2 },
    { XK_o,        3 },
    { XK_m,        4,4,4,4,4 },
    { XK_n,        5 },
};

**Comment by jbensmann** [comment]
No that does not work, one can only bind a key to different actions, e.g. click and execute a command.
