### ISSUE TITLE
When activating xmouseless with pressed movement key mouse will move in opposit direction on key release

### ISSUE THREAD

**Issue by pyriand3r** [jbensmann/xmouseless#3]
If you start xmouseless while holding a key that is defined as a movement key the cursor will not move until releasing the key. Then it will move in the opposit direction of the defined direction of the key.

For example i have set `i,j,k,l` for mouse movement. `j` will move the cursor to the left. When i press and hold `j` and then activate/start xmouseless while still holding `j` the mouse will not move until i release `j`. On key release the mouse will move to the right until i press `j` again.

**Comment by jbensmann** [comment]
It is assumed all keys are up when starting xmouseless, but it sometimes also happens to me that I press a movement key too early. I think the easiest fix would be to ask which keys are down once at start, I will try to do that.

**Comment by jbensmann** [comment]
Should be fixed.
